### ISSUE TITLE
Did you find a solution for this yet?

### ISSUE THREAD

**Issue by calvarez-ov** [DroidsOnRoids/android-resolve-test#1]
I found this project from this issue: https://discuss.gradle.org/t/configuration-canberesolved-returns-true-but-resolution-is-not-possible/24564

Looks like nobody replied to you over at gradle.org :(

I'm having this problem right now. Did you find a workaround for this?

Thanks!

**Comment by koral--** [comment]
Here is the workaround: https://github.com/koral--/gradle-pitest-plugin/commit/63194854fd1c4e1fffef34ff1b9a02ac6e3f4f31#diff-82b376865bfec078800b70e1186fd227

**Comment by calvarez-ov** [comment]
Awesome!! Thanks so much.
